= languagetool.el
Joar Buitago <jebuitragoc@unal.edu.co>
v0.1.0, 2020-01-21

Use LanguageTool as your Emacs grammar and spelling corrector.

This package was based on
link:https://github.com/mhayashi1120/Emacs-langtool/[mhayashi1120
Emacs-Langtool], it's intended to make a pipeline through Emacs and
parse JSON output, making it incompatible with the original version,
that's why this package is not a forked version and it's made from
scratch.



== Getting Started

The first thing you need is *Java*, so download and install it.

You also need to download
*link:https://languagetool.org/[LanguageTool] Desktop Version* from
its official page.

After download, extract the contents in the folder you want
(e.g. `~/.languagetool/`), you will need to say to the package where
is the `languagetool-commandline.jar` file in your `.emacs` file like:

[source,lisp]
----
(setq languagetool-language-tool-jar
      "~/.languagetool/languagetool-command-line-jar")
----

Or via customize.  It's preferred to use full path instead.

It's recommended to add a Java flag to process the files in UTF-8, so
you should add to your `.emacs`:

[source,lisp]
----
(setq languagetool-java-arguments '("-Dfile.encoding=UTF-8"))
----

And finally you should tell which language are you using by default in
your `.emacs` file like:

[source,lisp]
----
(setq languagetool-default-language "en-GB")
----



== Usage

There are 5 commands to use, and if you want you can bind they to a key.

- `languagetool-check` To check the active region or the buffer.
- `languagetool-clear-buffer` To delete all the buffer highlights.
- `languagetool-correct-at-point` To correct the warning at point.
- `languagetool-correct-buffer` To correct the whole buffer.
- `languagetool-set-language` To change correction language.

For this package the suggested keybinding is:

- `(global-set-key "\C-clc" 'languagetool-check)`
- `(global-set-key "\C-cld" 'languagetool-clear-buffer)`
- `(global-set-key "\C-clp" 'languagetool-correct-at-point)`
- `(global-set-key "\C-clb" 'languagetool-correct-buffer)`
- `(global-set-key "\C-cll" 'languagetool-set-language)`

Once you are correcting with build in functions it will pop-up a
correction buffer at the minibuffer, you only need to choose.



== Customizable Variables

For this package there is a few customizable variables that should be
set in order to take control of LanguageTool suggestions.

- `languagetool-java-bin` Sets the path to the JAVA executable, if it
  is in `PATH` only it's name is needed.
- `languagetool-java-arguments` If you need to pass arguments to JAVA
  set this variable.  It must be a list of strings, one string for
  each argument without spaces.
+
e.g.
+
[source,lisp]
----
(setq languagetool-java-arguments '("-flag1" "-flag2"))
;; or
(setq languagetool-java-arguments '("-flag" "argumentforflag")
----
- `languagetool-language-tool-jar` Sets the path of the LanguageTool
  command line jar file.  It's recommended to put the full path.
- `languagetool-language-tool-arguments` Sets arguments to pass to
  LanguageTool.  It must be a list of strings, one string for each
  argument without spaces.
+
e.g.
+
[source,lisp]
----
(setq languagetool-language-tool-arguments '("-flag1" "-flag2"))
;; or
(setq languagetool-language-tool-arguments '("-flag" "argumentforflag")
----
- `languagetool-default-language` Sets the LanguageTool correction
  language.  It can be changed via command with
  `languagetool-set-language`.
- `languagetool-mother-tongue` If set LanguageTool behaviour change to
  correct using `languagetool-default-language` but being aware of
  false friends.
- `languagetool-disabled-rules` Tells LanguageTool to ignore these
  rules when checking text.
- `languagetool-local-disabled-rules` As `languagetool-disabled-rules`
  tells LanguageTool to ignore these rules when checking text but it's
  buffer local, so if you want you can set it in your local variables
  comment.
